#Porta do Servidor
server.port=8080

#Conexão com Banco
spring.datasource.url=jdbc:sqlite:C:\Users\Rafael\AppData\Roaming\DBeaverData\workspace6\.metadata\sample-database-sqlite-1\Chinook.db
spring.datasource.username=postgres
spring.datasource.password=T14@dedsec

#DDL - como o hibernate trata a estrutura do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=aula03
